# Generated by Django 2.2.16 on 2020-11-11 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('diary', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='image')),
                ('spo', models.BooleanField()),
                ('tag', models.TextField(null=True)),
                ('perfume', models.ManyToManyField(blank=True, related_name='perfume', to='perfumes.Perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
